spring:
  application:
    name: spring-cloud-eureka


server:
  port: 8002

eureka:
  instance:
    hostname: peer3
  client:
    #将serviceUrl指向peer1
    service-url:
      defaultZone: http://peer1:8000/eureka/,http://peer2:8001/eureka/
