spring:
  application:
    name: spring-cloud-eureka


server:
  port: 8001

eureka:
  instance:
    hostname: peer2
  client:
    #将serviceUrl指向peer1
    service-url:
      defaultZone: http://peer1:8000/eureka/
